name: Auto Update Data

on:
  schedule:
    - cron: "0 */4 * * *"   # Runs every 4 hours
  workflow_dispatch:         # Allow manual run

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot script
      env:
        COINSTAT_API_KEY: ${{ secrets.COINSTAT_API_KEY }}
        BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
        BINANCE_SECRET_KEY: ${{ secrets.BINANCE_SECRET_KEY }}
      run: python ModelFile/LSTM_File/run_model.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto update data"
        git push
      continue-on-error: true
